import type { SolicitudFormState } from '@/lib/types'

function getPrevMonthDefaults(): { mes: string; anio: string } {
  const d = new Date()
  const prev = new Date(d.getFullYear(), d.getMonth() - 1, 1)
  return { mes: String(prev.getMonth() + 1), anio: String(prev.getFullYear()) }
}

const today = new Date().toISOString().split('T')[0]

/** Fecha local YYYY-MM-DD (para fecha de solicitud de alta al momento de guardar). */
export function fechaSolicitudLocalHoy(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

export function createInitialSolicitudFormState(): SolicitudFormState {
  const { mes, anio } = getPrevMonthDefaults()
  return {
    personal_id: 'general',
    tipo: '',
    fecha_solicitud: today,
    observaciones: '',
    alta_nombre: '',
    alta_dni: '',
    alta_cuil: '',
    alta_domicilio: '',
    alta_direccion_dni: '',
    alta_domicilio_real_provincia_codigo: '',
    alta_domicilio_real_localidad: '',
    alta_domicilio_real_codigo_postal: '',
    alta_domicilio_dni_provincia_codigo: '',
    alta_domicilio_dni_localidad: '',
    alta_domicilio_dni_codigo_postal: '',
    alta_fecha_nacimiento: '',
    alta_telefono: '',
    alta_email: '',
    alta_banco: '',
    alta_cbu: '',
    alta_puesto_id: '',
    alta_fecha_incorporacion: today,
    alta_fecha_inicio_cobro: today,
    alta_condicion_laboral: '',
    alta_fecha_alta_temprana: '',
    alta_jornada_dias_semanales: '',
    alta_jornada_horas_diarias: '',
    alta_propuesta_economica: '',
    alta_beneficios: '',
    alta_otras_observaciones: '',
    alta_doc_dni_archivos: [],
    alta_doc_ddjj_archivos: [],
    alta_doc_puesto_archivos: [],
    alta_doc_foto_url: '',
    alta_doc_foto_nombre: '',
    alta_doc_normas_archivos: [],
    alta_doc_uniforme_archivos: [],
    alta_periodo_prueba: false,
    alta_periodo_prueba_dias: '180',
    alta_carnet: false,
    alta_carnet_archivo_url: '',
    alta_carnet_archivo_nombre: '',
    alta_carnet_vencimiento: '',
    baja_fecha: today,
    baja_motivo_id: '',
    baja_motivo_detalle: '',
    baja_empleado_liquidacion: null,
    baja_carta_url: '',
    baja_carta_nombre: '',
    vacaciones_desde: today,
    vacaciones_hasta: today,
    vacaciones_dias: '',
    licencia_tipo: '',
    licencia_desde: today,
    licencia_hasta: today,
    licencia_motivo: '',
    licencia_constancia_url: '',
    licencia_constancia_nombre: '',
    apercibimiento_fecha: today,
    apercibimiento_severidad: 'Leve',
    apercibimiento_motivo: '',
    apercibimiento_archivo_url: '',
    apercibimiento_archivo_nombre: '',
    descuento_motivo: '',
    descuento_monto: '',
    descuento_fecha: today,
    horas_extras_cantidad: '',
    horas_extras_fecha: today,
    horas_extras_valor_hora: '',
    horas_extras_descripcion: '',
    nov_area_id: '',
    nov_mes: mes,
    nov_anio: anio,
    nov_empleados: [],
    suspension_fecha_desde: today,
    suspension_fecha_hasta: today,
    suspension_motivo: '',
    suspension_archivo_url: '',
    suspension_archivo_nombre: '',
    capacitacion_area_id: '',
    capacitacion_tema: '',
    capacitacion_fecha: today,
    capacitacion_descripcion: '',
    uniforme_talle: '',
    uniforme_items: '',
    adelanto_monto: '',
    adelanto_fecha: today,
    adelanto_motivo: '',
    incentivo_scope: 'colaborador',
    incentivo_area_id: '',
    incentivo_puesto_id: '',
    incentivo_descripcion: '',
    incentivo_monto: '',
    incentivo_fecha: today,
    incentivo_archivo_url: '',
    incentivo_archivo_nombre: '',
    cambio_nuevo_puesto_id: '',
    cambio_nueva_sucursal_id: '',
    cambio_fecha_efectiva: today,
    cambio_motivo: '',
  }
}
